### ISSUE TITLE
Experiment with applying reviews style to preface

### ISSUE THREAD

**Issue by karindalziel** [whitmanarchive/whitman-LG_1855_variorum#61]
I have altered the preface formatting to maintain inline text, and when I tried to apply this to the preface on the main variorum page, it didn't quite work. 

I have already included the class "tei_front" int he preface so we can try to style this later

code tries: 

```css.tei_front .v_container,
.tei_front .v_corresp,
.tei_front .v_xmlid,
.tei_front .variorum_content,
.v_reviews .v_container,
.v_reviews .v_corresp,
.v_reviews .v_xmlid,
.v_reviews .variorum_content {
  display: inline;
  margin: 0; padding: 0;
}

.tei_front .v_corresp,
.v_reviews .v_corresp {
  display: inline-block;
  margin: 0 10px 0 -90px; 
  padding: 0 10px 0 0;
  float: left;
}

.review, .tei_front {
  padding: 13px 80px 10px 100px;
  text-align: left;
}
```

![Screen Shot 2019-07-31 at 9 06 18 AM](https://user-images.githubusercontent.com/284315/62218876-e9b35b00-b372-11e9-8369-85e11f4559f7.png)
